### ISSUE TITLE
[🐛 bug][IDEA 2023.3.6] A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?

### ISSUE THREAD

**Issue by ChrisCarini** [ChrisCarini/loc-change-count-detector-jetbrains-plugin#359]
# User Description
_User did not enter any detailed information._

# Stack Trace
```
java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:130)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:388)
	at com.intellij.openapi.progress.impl.CoreProgressManager.suppressPrioritizing(CoreProgressManager.java:830)
	at com.intellij.openapi.progress.impl.CoreProgressManager.avoidBlockingPrioritizingThread(CoreProgressManager.java:886)
	at com.intellij.openapi.progress.impl.CoreProgressManager.isLowPriorityReallyApplicable(CoreProgressManager.java:865)
	at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:844)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:223)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:150)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:89)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.delegate(AbstractProgressIndicatorExBase.java:202)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:91)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.delegate(AbstractProgressIndicatorExBase.java:202)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:91)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:143)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:233)
	at git4idea.commands.GitTextHandler.waitForProcess(GitTextHandler.java:112)
	at git4idea.commands.GitHandler.runInCurrentThread(GitHandler.java:411)
	at git4idea.commands.GitImplBase.doRun(GitImplBase.java:194)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:158)
	at git4idea.commands.GitImplBase.runCommand(GitImplBase.java:63)
	at com.chriscarini.jetbrains.locchangecountdetector.git.GitNumStat.getGitCommandOutput(GitNumStat.java:48)
	at com.chriscarini.jetbrains.locchangecountdetector.git.GitNumStat.compute(GitNumStat.java:66)
	at com.chriscarini.jetbrains.locchangecountdetector.LoCService.getGitShowHeadNumStat(LoCService.java:80)
	at com.chriscarini.jetbrains.locchangecountdetector.LoCService$2.run(LoCService.java:97)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2023.3.6 Build: #IU-233.15026.9 March 20, 2024
Theme: IntelliJ Light
JRE: 17.0.10+1-b1087.23, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.23, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.4.1 (aarch64)

=== Plugins ===
Custom plugins: [Jupyter (233.14475.28), Code::Stats (1.0.9), String Manipulation (9.13.0), Go (233.15026.9), CodeMetrics (1.0.4), linkedin-loc-change-count-configurer (0.0.32), Scala (2023.3.29), Unit File Support (systemd) (223.240127.136), Lines of Code Change Observer (0.4.6), listudio (22.3.7), Environment Variable Settings Summary (3.2.6), Graph Database (0.8.0), ReStructuredText (233.11799.188), CheckStyle-IDEA (5.90.0), Logshipper (3.2.6), GraphQL (233.14808.14), Rust (233.25989.180), Sample Menu Action (0.6.6), Space (233.15026.16), Git Push Reminder (1.2.6), Automatic GitHub Issue Navigation Configuration (1.2.7), Iris (1.2.6), Sample Notification (3.2.6), Ini (233.15026.15), Developer Tools (4.2.0), JavaFX Runtime for Plugins (1.0.4), Automatic Power Saver (3.2.6), WakaTime (14.3.13), Python (233.15026.9), GitHub Copilot (1.5.3.5510), Bazel for IntelliJ (2024.04.09.0.1-api-version-233)]
Disabled plugins:[Ruby (233.15026.9), Cucumber for Groovy (233.15026.9), AI Assistant (233.15026.9)]
```

**Comment by ChrisCarini** [comment]
Haven't seen this in a while - closing.
